all: cat2 cat3 cat4 wc2

cat2: cat2.c
	gcc -Wall -fsanitize=address,undefined -o cat2 cat2.c

cat3: cat3.c
	gcc -Wall -fsanitize=address,undefined -o cat3 cat3.c

cat4: cat4.c
	gcc -Wall -fsanitize=address,undefined -o cat4 cat4.c

wc2: wc2.c
	gcc -Wall -fsanitize=address,undefined -o wc2 wc2.c
